### ISSUE TITLE
Specifying engine pool class in config

### ISSUE THREAD

**Issue by ericremoreynolds** [pallets/flask-sqlalchemy#266]
Hello,

SQLAlchemy's `create_engine` function has keyword argument `poolclass` allowing you to ovverride the default connection pool for the engine.

Is there any way to specify this in Flask-SQLAlchemy? Specifically I want to use a disk-based SQLite db with the `SingletonThreadPool` class.

Thanks in advance!

Eric.

**Comment by makmanalp** [comment]
I don't have a perfect answer but check out apply_driver_hacks and apply_pool_defaults here:

https://github.com/mitsuhiko/flask-sqlalchemy/blob/3d3c72faeef2f0195397cf84e788924395d280e9/flask_sqlalchemy/__init__.py#L791

**Comment by nbaggott** [comment]
I take it from the fact that this issue is still open that you are not suggesting subclassing FlaskSQLAlchemy.

I wanted to present another use case for setting the pool class (and offer to implement). I need to configure the pool class to the NullPool for scaling reasons. Here's a comment from my subclass explaining why this was necessary:
```
  Disable session pooling.

  The default QueuePool pool doesn't allow you to fully close a connection. Calling
  db.session.close() returns the session to the pool with the TCP connection
  still open and a new transaction started. Because of the state that mysql has to
  maintain for repeatable read isolation, long lived sessions are a drain on db
  resources and performance suffers. Under load the DB will terminate connections before 
  the configured timeout (but this is still too late to prevent performance problems).

  With the NullPool, sessions work as expected - db.session.close() actually terminates the
  TCP connection. (You can confirm behavior with 'netstat -ant |grep 3306')

  One might think that an app under constant load would recycle it's DB connections pretty
  frequently, starting new transactions in the process and reducing the number of long lived
  connections. This is not the case. Gunicorn does not round-robin across flask workers and
  we routinely see some flask workers not used for hours even when the app is under continuous
  load.
```
Let me know if you'd be open to a patch for configuring poolclass.  I've worked around the problem but have multiple apps with this requirement and it would be convenient if this option where directly settable via flask-sqlalchemy.

Thanks! 
   Nick

**Comment by ericremoreynolds** [comment]
FYI subclassing is the workaround I used in the end.

**Comment by tmeryu** [comment]
I was having a problem on AppEngine losing MySQL server connection. I was told to use NullPool to solve so I made this change: https://github.com/tmeryu/flask-sqlalchemy/commit/a20c309fb00d5eb19678c47a162afa2e35c38f87

I'll leave a pull request but I'm open to suggestions of how to improve the code.

**Comment by jdp** [comment]
Being able to specify `poolclass` to the engine, as well as `connect_args` would be super helpful for testing with in-memory SQLite databases. Right now it's not possible because an in-memory SQLite database is destroyed when a connection closes. Check out [this post](http://www.sameratiani.com/2013/09/17/flask-unittests-with-in-memory-sqlite.html) for more details.

**Comment by knabben** [comment]
up

**Comment by rsyring** [comment]
This will be taken care of by: https://github.com/pallets/flask-sqlalchemy/issues/166
