### ISSUE TITLE
Acronyms in tablename aren't converted to snake case

### ISSUE THREAD

**Issue by davidism** [pallets/flask-sqlalchemy#406]
Acronyms aren't being recognized as separate words when converting to snake case.  Only happens with plain acronyms or acronyms with a prefix but not a suffix.

``` python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
db = SQLAlchemy(app)

class ABC(db.Model):
    id = db.Column(db.Integer, primary_key=True)

class PreABC(db.Model):
    id = db.Column(db.Integer, primary_key=True)

class ABCPost(db.Model):
    id = db.Column(db.Integer, primary_key=True)

class PreABCPost(db.Model):
    id = db.Column(db.Integer, primary_key=True)

db.engine.echo = True
db.create_all()
```

```
CREATE TABLE "ABC" (
    id INTEGER NOT NULL, 
    PRIMARY KEY (id)
)

CREATE TABLE "preABC" (
    id INTEGER NOT NULL, 
    PRIMARY KEY (id)
)

CREATE TABLE abc_post (
    id INTEGER NOT NULL, 
    PRIMARY KEY (id)
)

CREATE TABLE pre_abc_post (
    id INTEGER NOT NULL, 
    PRIMARY KEY (id)
)
```

**Comment by davidism** [comment]
As far as I can tell it's always been this way.  I'm surprised no one commented on it before, since it's definitely not correct.

Changing this would be backwards incompatible because tablenames for existing tables could change.  However, it would be part of the 3.0 major version bump.

@immunda thoughts?

**Comment by rokob** [comment]
Yes, I just ran into this as well. I read the code, here is a possible fix.

Change
```
_camelcase_re = re.compile(r'([A-Z]+)(?=[a-z0-9])')
```
to
```
_camelcase_re = re.compile(r'([A-Z])(?=[a-z0-9])')
```
and then change `_join` to
```
def _join(match):
                word = match.group()
                if len(word) > 1 and word[-1].lower() == word[-1]:
                    return ('_%s_%s' % (word[:-1], word[-1])).lower()
                return '_' + word.lower()
```
and define this
```
_upcase_re = re.compile(r'([A-Z]+))
```

Then, the table names would come from
```
>>> _upcase_re.sub(_join, _camelcase_re.sub(_join, 'PreABCPost')).lstrip('_')
'pre_abc_post'
>>> _upcase_re.sub(_join, _camelcase_re.sub(_join, 'PreABC')).lstrip('_')
'pre_abc'
>>> _upcase_re.sub(_join, _camelcase_re.sub(_join, 'ABC')).lstrip('_')
'abc'
>>> _upcase_re.sub(_join, _camelcase_re.sub(_join, 'ABCPost')).lstrip('_')
'abc_post'
>>> _upcase_re.sub(_join, _camelcase_re.sub(_join, 'CamelCase')).lstrip('_')
'camel_case'
```

**Comment by immunda** [comment]
Good spot @davidism, I've never actually come across this either as I more or less always explicitly set `__tablename__`.

Seems like a sensible change too, @rokob.

The biggest hurdle is setting peoples expectations around the change. I'd like 3.0 to be free of lots of nuanced depreciation notices, I see two obvious solutions:

a) Inject another 2.x release which noisily warns users if they have any models which would be affected and how to fix it, i.e. with `__tablename__`.

b) Just make the change for 3.0 as it'll break loudly in folks' testing, but perhaps not as pleasant and more unexpected behaviour if people aren't diligent.

Thoughts, comments, concerns? Otherwise I'm leaning towards b) ;)

**Comment by justanr** [comment]
I think a 2.x warning would be nice. But I'm in the manually set tablename camp as well.
