### ISSUE TITLE
unit tests do not pass with on disk database

### ISSUE THREAD

**Issue by scotchka** [pallets/flask-sqlalchemy#422]
The unit tests are based on a connection to in-memory sqlite3, and break with on disk sqlite3 or PostgreSQL. Would it be a sensible effort to make the tests pass for those as well?

**Comment by davidism** [comment]
This could be modified by using pytest's `tmp_path` fixture to create a new database URI for each test in the `app` fixture. But there's not really a point, the tests use an in-memory database for speed and convenience. They shouldn't be dependent on how the database is configured because that's SQLAlchemy's job to abstract.
