### ISSUE TITLE
Ignore SQLALCHEMY_POOL_SIZE when using NullPool

### ISSUE THREAD

**Issue by jboegeholz** [pallets/flask-sqlalchemy#426]
When using sqlite as DB and SQLALCHEMY_POOL_SIZE is set to 0 sqlalchemy throws 
`TypeError: Invalid argument(s) 'pool_size' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine`

It would be great if the config param SQLALCHEMY_POOL_SIZE will be ignored in case of NullPool and a warning is issued by flask-sqlalchemy

**Comment by keiranmraine** [comment]
This is very problematic if you have tools configured to ensure all appropriate environment variables are set and provided.  The hard fail results in non-generic paths having to be introduced to handle running tests with SQLite.

**Comment by rsyring** [comment]
I've added some configuration tests in #684 to confirm FSA is doing "the right thing" and, as best I can tell, it is.

FSA does not set SQLALCHEMY_POOL_SIZE on it's own.  If a developer has set SQLALCHEMY_POOL_SIZE to zero explicitly, and is also using SQLite, then FSA is going to pass that through to SA no questions asked.  It's up to the developer, not FSA, to make sure that combination is not occurring.

You are welcome to post back if you think I'm missing something.  But I'm going to close this issue since I don't think we would make the change requested.
