### ISSUE TITLE
flask-sqlalchemy ignores the setting "app.json_encoder"

### ISSUE THREAD

**Issue by TimoStolz** [pallets/flask-sqlalchemy#450]
When I provide a customized json encoder, this will be ignored by flask_sqlalchemy.

Let's say I have:
```
from flask import Flask
app = Flask(__name__)
app.json_encoder = MyCustomJSONEncoder
```

Then this encoder should be used when creating the engine, like this:
```
sqlalchemy.create_engine(
   ..., 
   json_serializer=lambda o: json.dumps(o, cls=app.json_encoder),
   json_deserializer=lambda j: app.json_encoder.loads(j),
   ...)
```

**Comment by rsyring** [comment]
I think there is a symmetry here that I like.  However, I wonder if it would be somewhat unexpected for people if we implicitly did this.  If someone sets the JSON encoder on a Flask app, I wonder if it would make sense for them that the same encoder would be used with their DB connections.  I

 also wonder if setting those engine parameters for backends that don't support JSON (are there any?) would be problematic.

Since this would be new and potentially unexpected functionality, I think we need to leave this for 3.0.

**Comment by davidism** [comment]
Flask's encoder is intended for JSON responses, not for serializing data for the database, which might have its own requirements. I agree with @rsyring that it might cause confusion if used by default here. As you've shown, you can use Flask's encoder if you want with some engine options, but I don't think that's common enough to need to change anything right now.
