### ISSUE TITLE
Disable SQLALCHEMY_DATABASE_URI when SQLALCHEMY_BINDS is used

### ISSUE THREAD

**Issue by cykerway** [pallets/flask-sqlalchemy#663]
I don't see there is a need for `SQLALCHEMY_DATABASE_URI` when `SQLALCHEMY_BINDS` is used. If users don't set `SQLALCHEMY_DATABASE_URI` then it gets a default value of an in-memory sqlite database. This may confuse users if they forget to set `__bind_key__` on a model. In that case, that model doesn't fail but writes into the in-memory database.

I was trying to set `SQLALCHEMY_DATABASE_URI` to `None`, but flask-sqlalchemy doesn't seem to allow that with `db.create_all()`, even if all the models have `__bind_key__` set to a valid bind. Can you fix the plugin so that `SQLALCHEMY_DATABASE_URI` defaults to `None`, or at least let users set it to `None`? Thank you.

Possibly related to: https://github.com/mitsuhiko/flask-sqlalchemy/issues/471, #472

**Comment by rsyring** [comment]
I do believe we should remove the default value for `SQLALCHEMY_DATABASE_URI` and instead throw an error when the value is None and binds are not being used.  @davidism [has a comment](https://github.com/pallets/flask-sqlalchemy/pull/472#issuecomment-282918148) in #472 that indicates the current state of things is misleading.

Bumping this milestone to 3.0 since it would be a backwards incompatible change.

**Comment by lbeaufort** [comment]
Hi, I'd like to take on this issue :)

**Comment by davidism** [comment]
Merged #727, go ahead with a PR!

**Comment by Snyssfx** [comment]
I have several databases with the same structure and it's natural that I not define `SQLALCHEMY_DATABASE_URI`. 
Why is it need to throw a error?
