### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: Table 'users' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

### ISSUE THREAD

**Issue by vanangamudi** [pallets/flask-sqlalchemy#672]
Flask: 0.9
Flask-SA: 2.3.2
Flask-migrate:0.12.2

```
from app import db

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User {}>'.format(self.username)    
```

I am following the [tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database). When try importing the models file in python interpreter, I face this issue. [This closed issue](https://github.com/pallets/flask-sqlalchemy/issues/478) related to this one. But setting the __tablename__ to new name or none, neither seems to work.

**Comment by rsyring** [comment]
I don't believe this is likely to be a bug in Flask SQLAlchemy.  You are also using an unsupported version of Flask (we currently support 0.12+).  If you think this is still a bug in FSA, please open a new issue with a new example.  Thanks.

**Comment by CT83** [comment]
We faced this exact same bug in production.
The code worked fine for the developer who wrote it but not for me or in production.
This had happened once before as well.

Turns out there were older leftover .pyc files in directories which were deleted in subsequent commits. 

So, basically we hit the union of two problems.
1. Having left over .pyc files on the disk.
2. Git Ignoring empty directories full of files in **.gitignore**

Deleting the directories and cleaning the .pyc files solved the problem. 

Did not see many answers with suggesting this as a fix, so thought I would chip in.

**Comment by nk9** [comment]
CT83, you're a life saver! Had added an Enum column to my Postgres database, and Flask-Admin kept giving me this error. Deleted all .pyc files in the relevant Blueprint subfolders, and everything is back to normal again. Many thanks.

**Comment by maozhenzhong** [comment]
[db.metadata.clear()](https://blog.csdn.net/BridgeHong/article/details/88999316)这个方法解决了我的问题，你可以尝试一下

**Comment by ThiefMaster** [comment]
Why do you think we speak/understand chinese?

**Comment by RolandoRetana** [comment]
I want to add a comment in case someone has the same problem as I had. In one of the files I was importing the mode as 
`from models.user import User`
and in the other file I was using:
`from myProject.models.user import User`

This somehow cause it to be seen as 2 different models. It took me a while to realize.

**Comment by zaraki02** [comment]
First try db.create_all( )...Trust me it will work, where u created ur models for the database...Happy coding!
