### ISSUE TITLE
Add Mac/Windows CI builds

### ISSUE THREAD

**Issue by rsyring** [pallets/flask-sqlalchemy#690]
Flask has Windows CI: https://github.com/pallets/flask/blob/master/.appveyor.yml

But [removed support for MacOS](https://github.com/pallets/flask/commit/537df96632f12c2bd2cb5ae933844229f029f7b5).

**Comment by paxnovem** [comment]
Since this was created, mac builds were added back when flask switched to azure pipelines. I am going to try to make a PR this coming weekend for this, but I will probably do it by switching it to azure pipelines for consistency with other pallets projects. Unless there was a reason we didn't switch.

**Comment by davidism** [comment]
Yes, please switch everything to Azure, should mostly only have to copy the config from another of the projects. I can set up an Azure project once it's ready.

**Comment by davidism** [comment]
Switched to GitHub Actions in #823.
