### ISSUE TITLE
Create GitHub issue template for new issues

### ISSUE THREAD

**Issue by rsyring** [pallets/flask-sqlalchemy#728]
I'd like to see FSA have an issue template that would show up when users create new issues that asks them to provide:

* OS Details
* Python, SQLAlchemy, and Flask-SQLAlchemy versions
* A [MCVE](https://stackoverflow.com/help/mcve)
* A reminder that FSA is a thin wrapper that combines Flask and SQLAlchemy and to double-check that their issues is really an FSA issue and not an SQLAlchemy issue before submitting.
* A reminder that GitHub issues are not to be used for support requests and point them to other places (Stack Overflow) for that kind of help.
* A reminder to **be extra nice** since [unkind people are the hardest part about maintaining OSS](https://www.youtube.com/watch?v=tzFWz5fiVKU&feature=youtu.be&t=49m32s)??

**Comment by lbeaufort** [comment]
Hi @rsyring I'm happy to work on this issue.

**Comment by lbeaufort** [comment]
@rsyring here's what I have so far. Any changes before I put in a PR?

---
**This issue tracker is a tool to address bugs in Flask-SQLAlchemy itself.
Please use the [#pocoo IRC channel on freenode](http://flask.pocoo.org/community/irc/) or [Stack Overflow](https://stackoverflow.com/questions/tagged/flask-sqlalchemy?sort=linked) for general
questions about using Flask-SQLAlchemy or issues not related to Flask-SQLAlchemy.**

If you'd like to report a bug in Flask-SQLAlchemy, fill out the template below.
Provide any extra information that may be useful / related to your problem.
Ideally, create a [minimal, complete, and verifiable example (MCVE)](https://stackoverflow.com/help/mcve), which helps us
understand the problem and helps check that it is not caused by something in
your code.

Flask-SQLAlchemy is a thin wrapper that combines [Flask](https://github.com/pallets/flask) and [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy). Please check 
if your issue has already been reported as a [SQLAlchemy issue on Github](https://github.com/sqlalchemy/sqlalchemy/issues).

Also, please be kind - this project is maintained by volunteers. We appreciate
you taking the time to provide the information needed to address your issue.

---

### Expected Behavior

Tell us what should happen.

```python
Paste a minimal example that causes the problem.
```

### Actual Behavior

Tell us what happens instead.

```pytb
Paste the full traceback if there was an exception.
```

### Environment

* Operating system:
* Python version:
* Flask-SQLAlchemy version:
* SQLAlchemy version:

**Comment by rsyring** [comment]
@lbeaufort thank you for getting this started.  Can you go ahead and create the PR.  I do have some feedback but the PR interface will give us a better UI to interact on specific lines.
