### ISSUE TITLE
How to connect db before app run?

### ISSUE THREAD

**Issue by luoling1993** [pallets/flask-sqlalchemy#759]
I want to init something in my blue_print, I implemented it with classmethod. And in the classmethod, I should connect to the db. But get some error`No application found. Either work inside a view function or push`.
```python
# factory.py
app = Flask(__name__)
db.init_app(app)
with app.app_context():
    db.create_all(app=app)
app.register_blueprint(bp)  # blue print


# api.py
def init():
    SomeClass.init()
bp = Blueprint('bp', __name__, init)

# someclass.py
class SomeClass(object):
    @classmethod
    def init(cls):
        # some logit must be connect to db and query
        pass
```
I want to initialization the config from db while app run.

**Comment by ThiefMaster** [comment]
Ideally you don't, creating the database structure doesn't belong in the webapp part at all. It should be a separate script you run explicitly.

Anyway, if you push an app context it will work. Outside an app context it won't.

For any followup questions go to Stack Overflow, IRC or Discord since this is not the right place for support questions.
