### ISSUE TITLE
Paginator inconsistent with query results

### ISSUE THREAD

**Issue by aropie** [pallets/flask-sqlalchemy#774]
I'm working with a MySQL database. The problem is that when comparing `len(session.query(SomeModel).all()) ` with `session.query(SomeModel).paginate().total` I'm getting different results. Any insight on what the problem may be?

**Comment by ThiefMaster** [comment]
Does `session.query(SomeModel).count()` give you the correct result?

Also, this is probably an sqlalchemy issue and not specific to flask-sqlalchemy, since all `paginate()` does is [calling `.count()`](https://github.com/pallets/flask-sqlalchemy/blob/4c48fe42cc8a3ab3adcb4dcfa3db97fb025f6f04/flask_sqlalchemy/__init__.py#L510).

**Comment by aropie** [comment]
You're right, its related to how SQLAlchemy handles relations. Found the answer **[here](https://groups.google.com/forum/#!topic/sqlalchemy/iqkl3PB10kM)**.

Closing...
