### ISSUE TITLE
not able to connect to MSSQL database with bind , db owner is not working with schema . access denied error is occuring  

### ISSUE THREAD

**Issue by bharatpk0** [pallets/flask-sqlalchemy#806]
my Bind connection string for multiple databse 

{"DB_EDW_REP":"mssql+pyodbc://user:password@12iVe@servername/EDW_REP?driver=SQL+Server"}

my model 

class OneCaseTask(db.Model):
    __bind_key__  = 'DB_EDW_REP'
    __tablename__  = "TASK_BASE"
    __table_args__ = {'schema': "ONE_CASE"} # owner
    CASE_ID = db.Column(db.Integer, primary_key=True)
    TASK_ID = db.Column(db.Integer)
    OVRG_AMT_TOTAL = db.Column(db.Float(7,2))

    def __init__(self, name, price, store_id):
        self.CASE_ID = CASE_ID
        self.TASK_ID = TASK_ID
        self.OVRG_AMT_TOTAL = OVRG_AMT_TOTAL

please help me

**Comment by CoburnJoe** [comment]
Hi @bharatpk0 if you're getting access denied errors, it seems likely that your DB user is incorrect.

Perhaps the user does not exist, the password is wrong, or you don't have access to read or write from those tables. 

I don't think this is caused by flask-sqlalchemy, but if you can share your whole error message I'll gladly take a look.

**Comment by CoburnJoe** [comment]
Not related to flask-sqlalchemy. Post on Stack Overflow or DM me if you need further help.
