### ISSUE TITLE
Improve wiring for class based applications.

### ISSUE THREAD

**Issue by WolfgangFahl** [pallets/flask-sqlalchemy#903]
### Expected Behavior

I am trying to fix https://github.com/WolfgangFahl/pyFlaskBootstrap4/issues/9 to provide a high level "login" Blueprint.

It should be possible to use a database Model within a Blueprint without using global variables. The code below does not work due to the sequence of initialization steps.

An import is needed which fires before the main Example App's constructor can initialize things.

instead of:
```
        import fb4.login
        self.loginBluePrint=fb4.login.LoginBluePrint(self.app)
```
there needs to be a way to bring the self.app.db.model into the blueprint code for reference that is non-standard compared to the documentation. Hopefully there is a good solution already which only needs to be documented.

```
class ExampleApp(AppWrap):
    '''
    flask app wrapped in class 
    '''
    
    def __init__(self):
        '''
        Constructor
        '''
        scriptdir = os.path.dirname(os.path.abspath(__file__))
        template_folder=scriptdir + '/templates'
   
        super().__init__(template_folder=template_folder)
        
        self.app.secret_key = 'dev'
        
        self.app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///:memory:'
        
        # set default button style and size, will be overwritten by macro parameters
        self.app.config['BOOTSTRAP_BTN_STYLE'] = 'primary'
        self.app.config['BOOTSTRAP_BTN_SIZE'] = 'sm'
        # app.config['BOOTSTRAP_BOOTSWATCH_THEME'] = 'lumen'  # uncomment this line to test bootswatch theme

        self.db = SQLAlchemy(self.app)
        self.csrf = CSRFProtect(self.app)
        import fb4.login
        self.loginBluePrint=fb4.login.LoginBluePrint(self.app)
```

```
'''
Created on 19.01.2021

@author: wf
'''
from flask import Blueprint, redirect,render_template,request, flash, Markup, jsonify, url_for
from flask_wtf import FlaskForm, CSRFProtect
from flask_login import LoginManager,UserMixin
from flask_login import current_user, login_user,logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from wtforms import StringField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Length

class LoginBluePrint(object):
    
    instance=None
    '''
    a blueprint for logins
    '''
    def __init__(self,app,name:str,welcome:str="index",template_folder:str=None):
        '''
        construct me
        
        Args:
            name(str): my name
            welcome(str): the welcome page
            template_folder(str): the template folder
            
        '''
        self.name=name
        self.welcome=welcome
        if template_folder is not None:
            self.template_folder=template_folder
        else:
            self.template_folder='templates'    
        self.blueprint=Blueprint(name,__name__,template_folder=self.template_folder)
        self.app=app
        self.login = LoginManager(app)
        self.hint=None
        app.register_blueprint(self.blueprint)
        instance=self
        
    def loginForm(self):
        '''
        show the login form
        '''
        form = LoginForm()
        if current_user.is_authenticated:
            return redirect(url_for('index'))
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            if user is None or not user.checkPassword(form.password.data):
                flash('Invalid username or password')
                if self.hint is not None:
                    flash(self.hint)
                return redirect(url_for('login'))
            login_user(user, remember=form.rememberMe.data)
            return redirect(url_for(self.welcome))
        return render_template('login.html', form=form)
    
    def logOut(self):
        logout_user()
        return redirect(url_for(self.welcome))
    
    def addUser(self,db,username,password):
        '''
        add a user with the given username and password
        
        Args:    
            db: the SqlAlchemy database connection
            username(str): the username for the user
            password(str): the password for the user - only a hash will be stored
        '''
        u=User(id=1,username=username)
        u.setPassword(password)
        db.session.add(u)
        db.session.commit()


class LoginForm(FlaskForm):
    '''
    a form with username/password
    '''
    username = StringField('Username', validators=[DataRequired(), Length(1, 50)])
    password = PasswordField('Password', validators=[DataRequired(), Length(8, 150)])
    rememberMe = BooleanField('Remember me')
    submit = SubmitField('Login')
        
# connect to instance of the app
lbp=LoginBluePrint.instance        
db=lbp.app.db

# User handling
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    pass

    def setPassword(self, password):
        self.password_hash = generate_password_hash(password)

    def checkPassword(self, password):
        return check_password_hash(self.password_hash, password)

def __repr__(self):
    return '<User {}>'.format(self.username)

@lbp.blueprint.route('/login',methods=['GET', 'POST'])
def login():
    return lbp.loginForm()

@lbp.blueprint.route('/logout')
def logout():
    return lbp.logOut()
```
 
### Actual Behavior
more questions than answers see

    https://stackoverflow.com/questions/47636610/flask-sqlalchemy-mssqlpyodbc-and-existing-models-with-blueprint issue comes up ...
    https://stackoverflow.com/questions/60184852/removing-gloabl-app-reference-from-blueprint-in-flask
    https://stackoverflow.com/questions/55782492/creating-flask-sqlalchemy-instance-with-metadata-from-blueprint?rq=1
    https://stackoverflow.com/questions/53223826/adding-a-flask-class-instance-into-a-loginmanager-class-instance
    https://stackoverflow.com/questions/65225026/how-do-i-create-a-flaks-sql-alchemy-db-in-a-flask-blueprint

### Environment

* Python version: 3.6+
* Flask-SQLAlchemy version: as per base framework bootstrap-flask
* SQLAlchemy version: as per base framework bootstrap-flask

**Comment by davidism** [comment]
You don't create a `db` instance in a blueprint. I'm sorry, this design just doesn't make sense, but it's also too much code for me to try to review and debug. It also looks like you're trying to reinvent blueprints or something, but that's really not how you should go about things.

**Comment by ThiefMaster** [comment]
(but you are of course welcome to join https://discord.gg/pallets and discuss things there)

**Comment by WolfgangFahl** [comment]
I don't want to create a db instance in a blueprint. I'd love to use it. With a couple of thousand views quite a few questions on stackoverflow revolve around this problem and I thought it would be worthwhile to systematically solve it

**Comment by davidism** [comment]
I'm all for solving problems too. The problem here is that it's not clear what problem you're trying to describe. When reporting an issue, provide a *minimal* reproducible example, don't describe "actual behavior" as "see all these confused users on SO", and clearly describe the problem you're trying to solve. I looked at those links, and none of the questions seem related to the code you've shown, or directly contradict your statement about (mistakenly) wanting the db in the blueprint.

It seems like maybe you're trying to define a model in an extension? That's not really possible, as it's up to the user to define the db object and their models, not the extension. Other extensions have dealt with this problem (requiring another initialized extension to work), some solutions include:

1. Provide a mixin / abstract class with the interface you expect, including required properties and methods for querying. Users inherit from that, then pass their model when initializing the extension. This allows using any backing database, not just SQLAlchemy. (Flask-Login's `UserMixin` is an example of this.)
2. Provide decorators for registering functions to make the queries you need. This again allows using any database. (And again, Flask-Login's `@user_loader` is an example of this.)
3. As a variation on (1), require the user to use SQLAlchemy, and have them pass in their model. Your code will make the queries, they don't have to write methods to match an interface. This lets the user write less code, at the expense of only supporting SQLAlchemy (or whatever libraries you decide to detect).

Any of these solutions would have to be adapted further to support the `init_app` pattern so the extension does not store the app or model objects directly.

Again, the code you've shown *really* doesn't make sense, and should probably be redesigned. "Class based applications" are not a thing, and it's just adding an extra layer of indirection for no reason in your code. If you're trying to write an extension, you may want to refer to other extensions to see how they handle configuration and customization. Asking about your design is better handled on our Discord questions channel.

**Comment by WolfgangFahl** [comment]
Thank you for sharing your opinion "_Class based applications" are not a thing, and it's just adding an extra layer of indirection for no reason in your code."_

The difference in opinion seems to be the root cause for the difference in approach. The Class based approach works much better for my usecases so far and i hope to be able to continue to use it for the better separation of concerns. I'll look into your suggestions and try to better describe what I'd like to achieve. One of the goals is better debugging by making sure that the different parts needed for a  component of solution are all in one place (code, templates, model and so on ...)

**Comment by davidism** [comment]
You *can* use a class, it's not going to prevent anything you say it's preventing, but it requires a different design than what you've come up with, and is not necessary.
